# Generated by Django 5.2.6 on 2025-09-20 11:17

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="body",
            field=wagtail.fields.StreamField(
                [("hero_with_bullets", 11)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Small tagline above the title (e.g. 'Pride in Professionalism, Quality and Service').",
                            "required": False,
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Main headline (e.g. 'ACS Electrical Contractors').",
                            "required": True,
                        },
                    ),
                    2: (
                        "wagtail.blocks.TextBlock",
                        (),
                        {
                            "help_text": "Supporting text/intro paragraph.",
                            "required": False,
                        },
                    ),
                    3: ("wagtail.blocks.CharBlock", (), {"required": False}),
                    4: ("wagtail.blocks.URLBlock", (), {"required": False}),
                    5: ("wagtail.blocks.CharBlock", (), {"required": True}),
                    6: ("wagtail.blocks.StructBlock", [[("text", 5)]], {}),
                    7: (
                        "wagtail.blocks.ListBlock",
                        (6,),
                        {
                            "help_text": "List of value bullets (e.g. Experienced Team, Safety First)."
                        },
                    ),
                    8: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"required": False},
                    ),
                    9: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Years of experience badge (e.g. '30+').",
                            "required": False,
                        },
                    ),
                    10: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Experience caption (e.g. 'Years of experience, Lewiston–Auburn & beyond').",
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("tagline", 0),
                                ("title", 1),
                                ("description", 2),
                                ("primary_button_text", 3),
                                ("primary_button_url", 4),
                                ("secondary_button_text", 3),
                                ("secondary_button_url", 4),
                                ("bullets", 7),
                                ("image", 8),
                                ("experience_years", 9),
                                ("experience_text", 10),
                            ]
                        ],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
