# Generated by Django 5.2.6 on 2025-09-06 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20250906_1530'),
    ]

    operations = [
    ]
